<<<<<<< HEAD
SELECT 'YOUNGEST' AS TYPE,
NAME,
BIRTHDAY
FROM worker
WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker)
UNION
SELECT 'OLDEST' AS TYPE,
NAME,
BIRTHDAY
=======
SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM worker
WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker)
UNION
SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
>>>>>>> master
FROM worker
WHERE BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM worker)
